config/routes.rb
Rails.application.routes.draw do
  root to: "search#index"
  resources :search, only: [:index, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article
  attr_reader :headline, :link, :article_type, :word_count, :lead_paragraph

  def initialize(properties = {})
    @headline = properties[:headline][:main]
    @link = properties[:web_url]
    @lead_paragraph = properties[:lead_paragraph]
    @article_type = properties[:type_of_material]
    @word_count = properties[:word_count]
  end

  def self.create(article_data)
    article_data.map do |data|
      Article.new(data)
    end
  end
end

app/models/search.rb
class Search < ApplicationRecord
  validates_presence_of :keyword
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :find_searches
  before_action :check_search_box, only: [:create]
  before_action :find_articles, only: [:create]

  def index
    render :index
  end

  def create
    search = Search.find_or_create_by(keyword: key_word[:q])
    search.increment!(:count)

    render :index
  end

  private

  def check_search_box
    unless key_word[:q].present?
      flash[:errors] = "Please enter a keyword"
      redirect_to root_path
    end
  end

  def find_searches
    @searches = Search.order(created_at: :desc)
  end

  def find_articles
    article_data = ArticleService.search(key_word[:q])

    if article_data.is_a?(Hash) && article_data[:errors].present?
      flash[:errors] = article_data[:errors]
      redirect_to root_path
    else
      @articles = Article.create(article_data)
    end
  end

  def key_word
    params.require(:search).permit(:q)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimesArticleSearch</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/search/index.html.erb
<div class="nav">
  <h2 class="title">Welcome to the Times Article Search</h2>
  <p class="description">Search New York Times Articles by Keyword</p>
</div>


<div class="notification">
  <%= flash[:errors] %>
</div>

<div class="search">
  <%= form_for :search, url: search_index_path, method: :post do |f| %>
    <%= f.text_field :q, placeholder: "Enter Key Word", class: "search-box" %>
    <%= f.submit "Search", class: "search-button" %>
  <% end %>
</div>

<div class="search-container">
  <div class="past-searches">
    <h2>Past Searches</h2>
    <% if @searches %>
      <% @searches.each do |search| %>
        <p>
          Key Word: <%= link_to "#{search.keyword}",
                        search_index_path(search: { q: search.keyword }),
                        method: :post,
                        class: "link" %>
          <br>
          Search Count: <%= search.count %>
        </p>
      <% end %>
    <% end %>
  </div>

  <div class="results">
    <h2>Search Results</h2>
    <% if @articles %>
      <% @articles.each do |article| %>
        <h3>Headline: <%= article.headline %></h3>
        <p>Lead Paragraph: <i><%= article.lead_paragraph %></i></p>
        <p>Article Type: <%= article.article_type %></p>
        <p>Word Count: <%= article.word_count %></p>
        <%= link_to "Check out the Article", article.link, class: "link" %>
      <% end %>
    <% end %>
  </div>
</div>